apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret-db
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-db
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: secret-db
                key: user
        volumeMounts:
           - mountPath: /var/lib/postgres/data
             name: postgresdata
        ports:
          - containerPort: 5432
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim